bugfixes
jazzband/django-sortedm2m pull request #170
Opened 2020-08-19 14:33 UTC by amirouche

2020-08-19 14:48 UTC, auvipy requested changes
is it possible to add some tests for this change?

2020-08-19 15:16 UTC, amirouche commented
Sure!

What tests do you want? It is a frontend matter, so it will require some headless browser thing. Looking at the current repository there seems to be no such thing.

2020-08-19 15:17 UTC, amirouche commented
We also need to think how to run the tests inside travis. I have no experience with selenium + travis.

2020-08-20 08:01 UTC, amirouche commented on sortedm2m/static/sortedm2m/widget.js
>                      label = currentElement.siblings('label');
This will break I think if there is multiple `currentElement.siblings` return several nodes.

2020-08-20 12:31 UTC, amirouche commented on sortedm2m/static/sortedm2m/widget.js
>                      label = currentElement.siblings('label');
Actually no.

2020-08-20 12:33 UTC, amirouche commented
> is it possible to add some tests for this change?

@auvipy We are :100: % willing to contribute the necessary code to allow to test frontend aspects. Let me know what you think, in particular what will be your favorite headless browser testing software?

Thanks in advance!

2020-08-20 12:41 UTC, auvipy requested changes
you can use qunit?

2020-08-28 12:58 UTC, amirouche commented
I added a a minimal example file that demonstrate the bug in the following commit: https://github.com/jazzband/django-sortedm2m/pull/170/commits/08b39757f1a41f7d8f758f18652b4f752c950745

2020-08-28 12:58 UTC, amirouche commented
Let me know how do you want to proceed.

2020-08-28 15:56 UTC, auvipy commented
pylint --rcfile=pylintrc example sortedm2m sortedm2m_tests test_project *.py

************* Module sortedm2m.forms

sortedm2m/forms.py:23:16: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)

sortedm2m/forms.py:90:19: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)

************* Module sortedm2m.fields

sortedm2m/fields.py:39:27: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)

sortedm2m/fields.py:44:21: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)

sortedm2m/fields.py:50:12: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)

sortedm2m/fields.py:151:8: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)

sortedm2m/fields.py:187:8: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)

sortedm2m/fields.py:194:35: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)

sortedm2m/fields.py:203:12: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)

sortedm2m/fields.py:223:19: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)

sortedm2m/fields.py:271:15: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)

2020-08-28 15:58 UTC, auvipy approved these changes
Looks good

2020-09-02 10:36 UTC, amirouche commented
I tried to silence the only new quality error:

> test_project/qunit-runner.py:4:0: E0611: No name 'webdriver' in module 'selenium' (no-name-in-module)

Seems like the keyword is not `noqa`.

2020-09-02 21:20 UTC, clintonb commented
https://github.com/jazzband/django-sortedm2m/pull/172 was merged to fix the pylint issues. Rebase and I'll merge.

2020-09-02 21:20 UTC, clintonb approved these changes

2020-09-06 03:49 UTC, merged